# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

stages:
- stage:
  displayName: Obtener Aplicacion
  jobs:
    - job: 
      steps:
      - script: echo Descargando la App!
        displayName: 'Descargando la App'
- stage:
  displayName: 'Compilando la aplicacion'
  jobs:
    - job: 
      steps:
      - script: mvn install -DskipTests
        displayName: 'Instalando la app con Maven2'        
- stage:
  displayName: 'Realizando Pruebas de QA'
  jobs:
    - job: 
      steps:
      - script: echo Pruebas de Calidad de Sofware!
        displayName: 'Calidad de Software'
- stage:
  displayName: 'Realizando Pruebas de Seguridad'
  jobs:
    - job: 
      displayName: Generando Analisis en Fortify on Demand
      steps:
      - script: fcli fod session login $(Build.Repository.Name) --tenant=FranklinBank --user="Edwin Guerrero" --password=UTB6azg1Z1E9MXRsY0VyRCZyN2RjLmZVUkNBZllL0 --url=https://api.ams.fortify.com/
        displayName: 'Autenticando a Fod'
      - script: scancentral package -bt mvn -bf pom.xml -oss -o shoppingCart.zip
        displayName: 'Empaquetando el codigo fuente'
      - script: fcli fod sast start --purchase-entitlement --entitlement-id=11948 --entitlement-preference=SubscriptionOnly  --in-progress-action=Queue --file=shoppingCart.zip 958725 --session=$(Build.Repository.Name)
        displayName: 'Enviando el escaneo a FoD'
      - script: fcli fod session logout $(Build.Repository.Name)
        displayName: 'Desconectando de FoD'
      
- stage:
  displayName: 'Publicando Artefacto'
  jobs:
    - job: 
      steps:
      - script: echo Publicando App!
        displayName: 'Publicando App'