# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

stages:
- stage:
  displayName: Obtener Aplicacion
  jobs:
    - job: 
      steps:
      - script: echo Descargando la App!
        displayName: 'Descargando la App'
- stage:
  displayName: 'Compilando la aplicacion'
  jobs:
    - job: 
      steps:
      - script: mvn install -DskipTests
        displayName: 'Instalando la app con Maven2'        
- stage:
  displayName: 'Realizando Pruebas de QA'
  jobs:
    - job: 
      steps:
      - script: echo Pruebas de Calidad de Sofware!
        displayName: 'Calidad de Software'
- stage:
  displayName: 'Realizando Pruebas de Seguridad'
  jobs:
    - job: 
      displayName: Generando Sesion en Fortify on Demand
      steps:
      - script: fcli fod -h
        displayName: 'Autenticando a Fod'
    - job: 
      displayName: Verificando que existe la version del App
      steps:
      - script: fcli fod -h
        displayName: 'Verificando existencia en FoD'
- stage:
  displayName: 'Publicando Artefacto'
  jobs:
    - job: 
      steps:
      - script: echo Publicando App!
        displayName: 'Publicando App'