# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

stages:
- stage:
  displayName: Obtener Aplicacion
  jobs:
    - job: 
      steps:
      - script: Descargando la App!
        displayName: 'Descargando la App'
- stage:
  displayName: 'Compilando la aplicacion'
  jobs:
    - job: 
      steps:
      - script: mvn install
        displayName: 'Instalando la app con Maven2'        


